services:
    nginx:
        hostname: nginx
        image: nginx:latest
        ports:
            - 8350:80
        restart: always
        tty: true
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d/
            - ./nginx/keys:/etc/nginx/keys
            - ./nginx/statics:/etc/nginx/static/statics
    pocketbasec:
        build:
            context: ./pocketbase_custom
            # target: Develop
        hostname: pocketbasec
        restart: always
        volumes:
            - ./pocketbase_custom/pbdata:/pocketbase/pb_data
            - ./pocketbase_custom/src:/root/pocketbase
        environment:
            - AUTHROOT=https://localhost:8350/auth/
        tty: true
    redis:
        hostname: redis
        image: redis:latest
        restart: always
        ports:
            - 6379:6379
    app:
        hostname: app
        build:
            context: ./app
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./app/src:/root/src
            - ./pocketbase_custom/pbdata/authPublic:/root/src/authPublic
            - ./pocketbase_custom/pbdata/authPublic:/authPublic
        tty: true
        depends_on:
            - postgres
            - pocketbasec
    location:
        hostname: location
        build:
            context: ./location
            dockerfile: Dockerfile
            target: Develop
        restart: always
        volumes:
            - ./location/src:/root/src
            - ./pocketbase_custom/pbdata/authPublic:/root/src/authPublic
            - ./pocketbase_custom/pbdata/authPublic:/authPublic
        tty: true
        depends_on:
            postgres:
                condition: service_healthy
    postgres:
        image: postgres:17.3-alpine3.21
        hostname: postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        volumes:
            - db-store:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: 'user'
            POSTGRES_PASSWORD: 'postgres'
            POSTGRES_DB: 'meecha'    
    # mysql:
    #     image: mysql:8.0.34
    #     hostname: mysql
    #     # ports:
    #     #     - 3306:3306
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #         TZ: Asia/Tokyo
    #     volumes:
    #         - ./databases/mysql/data:/var/lib/mysql
    #         - ./databases/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
volumes:
    db-store: