services:
    # リバースプロキシけんWeサーバ
    nginx:
        hostname: nginx
        image: nginx:latest
        ports:
            - 8350:8443
        restart: always
        tty: true
        volumes:
            - ./nginx/configs:/etc/nginx/conf.d/
            - ./nginx/keys:/etc/nginx/keys
            - ./nginx/statics:/etc/nginx/static/statics
    
    # 認証用コンテナ
    auth:
        hostname: auth
        # build:
        #     context: ./auth
        #     dockerfile: dockerfile
        #     # target: Release
        #     target: Develop
        image: mattuu0/authbase-auth
        tty: true
        stdin_open: true
        env_file:
            - ./openssl/jwtKeys/private.env
            - ./config/auth.env
        volumes:
            - ./auth/src:/root/src
            - ./auth/icons:/assets/icons
        restart: always
        depends_on:
            mysql:
                condition: service_healthy
    # ダッシュボード
    # dashboard:
    #     hostname: dashboard
    #     build:
    #         context: ./dashboard
    #         dockerfile: dockerfile
    #         target: Develop
    #     tty: true
    #     volumes:
    #         - distvol:/root/src/dist
    #         - ./dashboard/src:/root/src
    #     restart: always

    # 認証用コンテナ
    app:
        hostname: app
        build:
            context: ./app
            dockerfile: dockerfile
            target: Develop
        tty: true
        env_file:
            - ./openssl/jwtKeys/public.env
            - ./config/app.env
        volumes:
            - ./app/src:/root/src
        restart: always
        depends_on:
            mysql:
                condition: service_healthy
            auth:
                condition: service_started
    # locationコンテナ
    location:
        hostname: location
        build:
            context: ./location
            dockerfile: dockerfile
            target: Develop
        tty: true
        env_file:
            - ./openssl/jwtKeys/public.env
            - ./config/location.env
        volumes:
            - ./location/src:/root/src
        restart: always
        depends_on:
            mysql:
                condition: service_healthy
            auth:
                condition: service_started
    # データベース
    mysql:
        hostname: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            TZ: Asia/Tokyo
        volumes:
            - dbdata:/var/lib/mysql
            - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./database/script/init.sql:/docker-entrypoint-initdb.d/init.sql 
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "root", "-proot"]
            interval: 5s
            timeout: 10s
            retries: 5
    redis:
        hostname: redis
        image: redis:latest
        restart: always
        ports:
            - 6379:6379
volumes:
    dbdata: