services:
    nginx:
        hostname: nginx
        image: nginx:latest
        ports:
            - 8350:80
        restart: always
        tty: true
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d/
            - ./nginx/keys:/etc/nginx/keys
            - ./nginx/statics:/etc/nginx/static/statics
    pocketbasec:
        image: private-hub.tail6cf7b.ts.net:3000/meecha-auth
        build:
            context: ./pocketbase_custom
            # target: Develop
        hostname: pocketbasec
        restart: always
        volumes:
            - ./pocketbase_custom/pbdata:/pocketbase/pb_data
            - ./pocketbase_custom/src:/root/pocketbase
        environment:
            AUTHROOT: 'https://localhost:8350/auth/'
            GRPC_ADDR: ':9000'
            GRPC_KEY: 'ORVBHieON30gk8dBo3DkMRPkMhpiyKS2NARNkmKwJogJ4uDZmKfoivZOMj0Xx70T'
        tty: true
    redis:
        hostname: redis
        image: redis:latest
        restart: always
        ports:
            - 6379:6379
    app:
        image: private-hub.tail6cf7b.ts.net:3000/meecha-app
        hostname: app
        build:
            context: ./app
            dockerfile: Dockerfile
            # target: Develop
        restart: always
        volumes:
            - ./app/src:/root/src
            - ./pocketbase_custom/pbdata/authPublic:/root/src/authPublic
            - ./pocketbase_custom/pbdata/authPublic:/authPublic
        tty: true
        environment:
            GRPC_SERVER: 'pocketbasec:9000'
            GRPC_KEY: 'ORVBHieON30gk8dBo3DkMRPkMhpiyKS2NARNkmKwJogJ4uDZmKfoivZOMj0Xx70T'
            # DATABASE_DSN: 'host=postgres user=user password=postgres dbname=meecha port=5432 sslmode=disable TimeZone=Asia/Tokyo'
            DATABASE_DSN: 'root:root@tcp(mysql:3306)/meecha?charset=utf8mb4&parseTime=True&loc=Local'
        depends_on:
            - database
            - pocketbasec
    location:
        image: private-hub.tail6cf7b.ts.net:3000/meecha-location
        hostname: location
        build:
            context: ./location
            dockerfile: Dockerfile
            # target: Develop
        restart: always
        environment:
            # DATABASE_DSN: 'host=postgres user=user password=postgres dbname=meecha port=5432 sslmode=disable TimeZone=Asia/Tokyo'    
            DATABASE_DSN: 'root:root@tcp(mysql:3306)/meecha?charset=utf8mb4&parseTime=True&loc=Local'
        volumes:
            - ./location/src:/root/src
            - ./pocketbase_custom/pbdata/authPublic:/root/src/authPublic
            - ./pocketbase_custom/pbdata/authPublic:/authPublic
        tty: true
        depends_on:
            - database
    # postgres:
    #     image: postgres:17.3-alpine3.21
    #     hostname: postgres
    #     healthcheck:
    #         test: ["CMD-SHELL", "pg_isready -U postgres"]
    #         interval: 5s
    #         timeout: 5s
    #         retries: 5
    #     volumes:
    #         - db-store:/var/lib/postgresql/data
    #     environment:
    #         POSTGRES_USER: 'user'
    #         POSTGRES_PASSWORD: 'postgres'
    #         POSTGRES_DB: 'meecha'    
    database:
        image: mysql:8.0.34
        hostname: mysql
        # ports:
        #     - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            TZ: Asia/Tokyo
            MYSQL_DATABASE: meecha
        volumes:
            - db-store:/var/lib/mysql
            - ./databases/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
volumes:
    db-store:
        name: meecha-db-store