FROM golang:1.24.1-bullseye as Develop

# 各種ツールインストール
RUN apt update & apt install -y curl wget git 

# 作業ディレクトリを移動
WORKDIR /root/src

# AIR のインストール
RUN go install github.com/air-verse/air@latest

CMD ["air", "-c", ".air.toml"]

# Build 
FROM golang:1.24.1-bullseye as build

# 各種ツールインストール
RUN apt update & apt install -y curl wget git

# コピー
COPY ./src /root/src

# ディレクトリ移動
WORKDIR /root/src

# 依存モジュールインストール
RUN go mod download
# ビルド
RUN CGO_ENABLED=0 go build -x --ldflags "-s -w" -o /go/bin/app .

# 実行環境
FROM gcr.io/distroless/static-debian12 as Release
COPY ./src/templates /templates
COPY ./src/dashboard /dashboard
COPY --from=build /go/bin/app /
CMD ["/app"]