// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: user.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *User) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type NameSearchMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	APIKEY        string                 `protobuf:"bytes,1,opt,name=APIKEY,proto3" json:"APIKEY,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameSearchMessage) Reset() {
	*x = NameSearchMessage{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameSearchMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameSearchMessage) ProtoMessage() {}

func (x *NameSearchMessage) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameSearchMessage.ProtoReflect.Descriptor instead.
func (*NameSearchMessage) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *NameSearchMessage) GetAPIKEY() string {
	if x != nil {
		return x.APIKEY
	}
	return ""
}

func (x *NameSearchMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LabelSearchMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	APIKEY        string                 `protobuf:"bytes,1,opt,name=APIKEY,proto3" json:"APIKEY,omitempty"`
	Labels        []string               `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelSearchMessage) Reset() {
	*x = LabelSearchMessage{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelSearchMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelSearchMessage) ProtoMessage() {}

func (x *LabelSearchMessage) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelSearchMessage.ProtoReflect.Descriptor instead.
func (*LabelSearchMessage) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *LabelSearchMessage) GetAPIKEY() string {
	if x != nil {
		return x.APIKEY
	}
	return ""
}

func (x *LabelSearchMessage) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResult) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\bauthGrpc\":\n" +
	"\x04User\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\x12\x1a\n" +
	"\bUserName\x18\x02 \x01(\tR\bUserName\"?\n" +
	"\x11NameSearchMessage\x12\x16\n" +
	"\x06APIKEY\x18\x01 \x01(\tR\x06APIKEY\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"D\n" +
	"\x12LabelSearchMessage\x12\x16\n" +
	"\x06APIKEY\x18\x01 \x01(\tR\x06APIKEY\x12\x16\n" +
	"\x06labels\x18\x02 \x03(\tR\x06labels\"4\n" +
	"\fSearchResult\x12$\n" +
	"\x05Users\x18\x01 \x03(\v2\x0e.authGrpc.UserR\x05Users2\x9d\x01\n" +
	"\vauthService\x12E\n" +
	"\fSearchByName\x12\x1b.authGrpc.NameSearchMessage\x1a\x16.authGrpc.SearchResult\"\x00\x12G\n" +
	"\rSearchByLabel\x12\x1c.authGrpc.LabelSearchMessage\x1a\x16.authGrpc.SearchResult\"\x00B\tZ\a../grpcb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_user_proto_goTypes = []any{
	(*User)(nil),               // 0: authGrpc.User
	(*NameSearchMessage)(nil),  // 1: authGrpc.NameSearchMessage
	(*LabelSearchMessage)(nil), // 2: authGrpc.LabelSearchMessage
	(*SearchResult)(nil),       // 3: authGrpc.SearchResult
}
var file_user_proto_depIdxs = []int32{
	0, // 0: authGrpc.SearchResult.Users:type_name -> authGrpc.User
	1, // 1: authGrpc.authService.SearchByName:input_type -> authGrpc.NameSearchMessage
	2, // 2: authGrpc.authService.SearchByLabel:input_type -> authGrpc.LabelSearchMessage
	3, // 3: authGrpc.authService.SearchByName:output_type -> authGrpc.SearchResult
	3, // 4: authGrpc.authService.SearchByLabel:output_type -> authGrpc.SearchResult
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
